require:
  - ../rubocop-custom/stub_env_should_only_return_string
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

RSpec/HookArgument:
  EnforcedStyle: each
RSpec/ImplicitExpect:
  EnforcedStyle: should
RSpec/ExampleLength:
  Max: 15
RSpec/InstanceVariable:
  AssignmentOnly: true

# Metrics
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 20

# Style
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/SingleLineMethods:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/SymbolProc:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/MultilineTernaryOperator:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/WordArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/NestedParenthesizedCalls:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 140
Layout/SpaceInsideParens:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false

# Lint
Lint/SymbolConversion:
  EnforcedStyle: consistent

# Naming
Naming/VariableNumber:
  Enabled: false
